site_name: QuickOC
site_description: Documentaci칩n oficial de QuickOC
site_author: Cristobal Briones
repo_url: https://github.com/Mafriones/QuickOC.git  # Reempl치zalo por tu repositorio

theme:
  name: material  # O usa el tema por defecto de MkDocs
  palette:
    primary: blue
    accent: deep-purple

nav:
  - Inicio: index.md
  - Instalaci칩n: installation.md
  - Uso: usage.md
  - Configuraci칩n: config.md
  - Desarrollo: development.md
  - API Referencia: api.md

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
